### ISSUE TITLE
Strange value for event.result.time

### ISSUE THREAD

**Issue by ajdaniel** [fit52/results#13]
Check out this event.result object:

```js
{
	...others,
	firstEvent: true,
	name: "Jane Stockdill-Mander",
	noEvents: 1,
	notes: ["First Event"],
	pb: false,
	pos: 10,
	time: "PT16M4S",
}
```

I'm not sure what format the `time` property is meant to be. I thought it was meant to be a time in seconds? Or is it some sort of specialised string, like 16 minutes 4 seconds in this case?

**Comment by BenVardy** [comment]
The time value is what `moment.duration` outputs, converted to a string. If it's parsed with `moment.duration` you should be able to convert it to the correct format.

**Comment by ajdaniel** [comment]
ah, I hadn't realised it was a format made by moment, I shall try parsing using MomentJS
