### ISSUE TITLE
One runner has duplicate event records

### ISSUE THREAD

**Issue by ajdaniel** [fit52/results#18]
One runner has duplicates of the same event in their record: https://fit52.eu-gb.mybluemix.net/runners/7d72fe2e-34f6-49fa-a895-bc13d5d6988b

**Comment by BenVardy** [comment]
I just checked the database and it appears that the runner's records are fine.

**Comment by markvardy** [comment]
Looking at the web site, this affects all runners that have run multiple times. If the database is correct, then this feels like a scoping problem in a closure somewhere (maybe in [Runner.js](https://github.com/fit52/ui/blob/master/src/App/components/Runner.js)?) but my JS isn't good enough to spot it!

**Comment by ajdaniel** [comment]
Yep this was a UI issue (whoops) and is fixed in this commit: https://github.com/fit52/ui/commit/585e20e5e290b655f4938e9441898bc845d05d24

**Comment by ajdaniel** [comment]
(FYI: The problem was when I was rendering the table, there wasn't a specified `id` attribute for each row of the table of events, and so they all became the same row due to identical `id`s of `undefined`)
