### ISSUE TITLE
PBs not consistently flagged

### ISSUE THREAD

**Issue by markvardy** [fit52/results#23]
Some people's PBs are not being flagged correctly. For example:

* [Andrew Church](https://fit52.eu-gb.mybluemix.net/runners/7cf02105-81f4-4b5d-9531-50ee49703fa2) shows each time as a PB, when one is not (June 27th)
* [Connie Green](https://fit52.eu-gb.mybluemix.net/runners/53629e88-6753-4803-ac76-8bf5eb9c9fa6) shows one time not flagged as a PB when it should be (Feb 27th) and one that is flagged that shouldn't (March 13th)

There are probably more, I haven't done an exhaustive check yet.

**Comment by ajdaniel** [comment]
I wonder if we should make a script to re-evaluate all of the times for each runner to ensure PB. If it's robust, we could use that to determine PB instead of the ingestion script for example

**Comment by markvardy** [comment]
We kind of have that already - there's a [script to rebuild the db](https://github.com/fit52/results/blob/master/utils/rebuild.js) from "core data" (i.e. people's personal data and event data). Possibly we could use this each time instead? Even so I'd quite like to understand what's going wrong.

**Comment by markvardy** [comment]
Closed by #24
