### ISSUE TITLE
Event dates processed incorrectly since BST

### ISSUE THREAD

**Issue by markvardy** [fit52/results#29]
The event dates are being processed incorrectly since the clocks went forward. The last 4 dates on the [event list](https://fit52.eu-gb.mybluemix.net/events) show as Tuesdays - i.e. the day before the run, in each case - but the input data from the timer files is the correct date.

However, the timestamp in the files is something like this:

```
Position,Time,Lap," 22/05/2019 00:00:00 Block:1"
```

which may be causing the problem. Ben has verified that the dates are incorrect in the database so this isn't a display issue.

**Comment by markvardy** [comment]
It's more confusing than I thought.

The results processing is definitely parsing these dates incorrectly at entry time - presumably [this line](https://github.com/fit52/results/blob/master/src/event-input/getResults.js#L19) needs something to tell it not to adjust what it assumes is BST to GMT or UTC. As a result, the [event list](https://fit52.eu-gb.mybluemix.net/events) shows all dates since BST as being the day before they actually were.

However, the UI is either deliberately or accidentally dealing with this on the event page itself (e.g. ["May 7th"](https://fit52.eu-gb.mybluemix.net/events/28)), where the event page shows the correct date (May 8th) at the top even though the data in the database is wrong. Also, if you click on a participant link in the event (say, [Dave Williams](https://fit52.eu-gb.mybluemix.net/runners/0a487f6a-09df-4739-927d-4a996f21f40b)), the event is shown with the correct date in the participant's event list, again, despite the database having incorrect data. @ajdaniel any thoughts?

**Comment by ajdaniel** [comment]
Here's a quick first pass. Where the date of the event is registered as midnight of the day of the event, since the clocks went forward, the date in the database is now 11pm of the day before the event:

```json
{
	"course": 2,
	"date": "2019-06-04T23:00:00.000Z",
	"number": 30,
	"title": "June 4th 2019"
}
```

with `title` generated from the `date` property:

```js
title: moment(event.date).format('MMMM Do YYYY')
```

And when the event is correct in the event page, the code to generate the title is the same, but the key difference is that the code runs on the browser, not the server:

```js
dateString: moment(eventData.date).format('MMMM Do YYYY')
```

So perhaps the date/time/timezone is incorrect on the server, which causes the incorrect date being shown.

**Comment by ajdaniel** [comment]
One way I could possibly fix this is just process all of those date formats on the browser instead of the server

**Comment by ajdaniel** [comment]
weirdly, when I run the UI locally on my computer, I get a whole different set of dates!!!

locally:

![image](https://user-images.githubusercontent.com/867941/58990343-99d66e80-87dd-11e9-9bee-572b2d74ddfc.png)

production:
![image](https://user-images.githubusercontent.com/867941/58990357-a22ea980-87dd-11e9-99a1-03cc7458155e.png)

**Comment by markvardy** [comment]
Thanks @ajdaniel! I think my preferred fix is to get the dates right in the database first though ... 😉 - then see how it affects the UI?

**Comment by markvardy** [comment]
Dates for events 26, 27, 28, 29 & 30 manually adjusted & database rebuilt

**Comment by ajdaniel** [comment]
@markvardy I already adjusted the UI to perform consistently with dates but it also helped get the dates right too
