### ISSUE TITLE
Enhancement request to Event structure

### ISSUE THREAD

**Issue by ajdaniel** [fit52/results#5]
I have a request to change some of the structure for `event`:

Rename `stats` to `counts`:
```json
"counts": {
  "2krunners": 16,
  "5krunners": 18,
  "total": 34,
  "firstTimeRunners": 34,
  "personalBests": 0,
  "volunteers": 0
},
```

It doesn't make a huge difference, just easier to read

**Comment by ajdaniel** [comment]
It would be nice if `ageGrade` was expressed as a percentage, perhaps to 2 decimal places? so instead of `"0.896586376"` it would be `"89.66"`

**Comment by BenVardy** [comment]
Should `ageGrade` be stored as a percentage to 2 decimal places or should it just output in that format?

**Comment by ajdaniel** [comment]
I think it should be stored as a percentage to 2 decimal places, unless you can think of a reason where storing it otherwise might be useful somewhere else.

**Comment by BenVardy** [comment]
Okay.

**Comment by BenVardy** [comment]
Previous events need to be updated to the new format for age grade.

**Comment by BenVardy** [comment]
Age Grades formatted to 2dp (London db)

**Comment by ajdaniel** [comment]
Great stuff! I'll migrate the UI to the new DB
